version: '3'

services:
  app:
    build:
      context: .
      dockerfile: conf/app.Dockerfile
    image: cdocstore
    ports:
      - "127.0.0.1:8080:8000"

  dev:
    build:
      context: .
      dockerfile: conf/app.Dockerfile
    image: cdocstore
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - APP_DEBUG=1
    volumes:
      - ./data:/data
      - ./src:/app
